[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"

# SPA 라우팅을 위한 리다이렉트
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 성능 최적화를 위한 헤더 설정
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 정적 자산 캐싱
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[functions]
  node_bundler = "esbuild"

# 환경변수 예시 (실제 값은 Netlify 대시보드에서 설정)
# NEXT_PUBLIC_SUPABASE_URL = "https://your-project.supabase.co"
# NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-anon-key"
