[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

# 환경변수 예시 (실제 값은 Netlify 대시보드에서 설정)
# NEXT_PUBLIC_SUPABASE_URL = "https://your-project.supabase.co"
# NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-anon-key"
